name: Test & Validate Streamlit App

on:
  push:
    branches: [ main ]

jobs:
  streamlit-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validar execução Streamlit (modo headless)
      run: |
        nohup streamlit run app.py &
        sleep 10
        pkill streamlit
